"""jobstatus_triggers

Revision ID: 1fdb8ac6e246
Revises: d9a75d4a7b00
Create Date: 2025-07-09 13:55:45.205400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1fdb8ac6e246'
down_revision: Union[str, None] = 'd9a75d4a7b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobstatus_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on_job_id', sa.Integer(), nullable=False),
    sa.Column('on_job_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fire_job_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobstatus_triggers')
    # ### end Alembic commands ###
