"""jobs.timezone

Revision ID: d9a75d4a7b00
Revises: 506d3ec6a721
Create Date: 2025-06-12 10:17:19.047274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9a75d4a7b00'
down_revision: Union[str, None] = '506d3ec6a721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'timezone')
    # ### end Alembic commands ###
